name: scrybe
description: Flutter package for comparing different ASR models
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  sherpa_onnx:
    path: ../sherpa-onnx/flutter/sherpa_onnx/
  wav: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
