name: scrybe_benchmarking
description: Flutter package for comparing different ASR models
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  circular_buffer: ^0.12.0
  collection: ^1.19.0
  csv: ^6.0.0
  flutter:
    sdk: flutter
  flutter_recorder: ^1.0.0
  flutter_riverpod: ^2.6.1
  fuzzywuzzy: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  sherpa_onnx:
    path: ../sherpa-onnx/flutter/sherpa_onnx/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # Offline Models
    # - assets/models/sherpa-onnx-nemo-fast-conformer-transducer-en-24500/encoder.onnx
    # - assets/models/sherpa-onnx-nemo-fast-conformer-transducer-en-24500/decoder.onnx
    # - assets/models/sherpa-onnx-nemo-fast-conformer-transducer-en-24500/joiner.onnx
    # - assets/models/sherpa-onnx-nemo-fast-conformer-transducer-en-24500/tokens.txt

    # - assets/models/sherpa-onnx-nemo-parakeet_tdt_transducer_110m-en-36000/encoder.onnx
    # - assets/models/sherpa-onnx-nemo-parakeet_tdt_transducer_110m-en-36000/decoder.onnx
    # - assets/models/sherpa-onnx-nemo-parakeet_tdt_transducer_110m-en-36000/joiner.onnx
    # - assets/models/sherpa-onnx-nemo-parakeet_tdt_transducer_110m-en-36000/tokens.txt

    # - assets/models/sherpa-onnx-whisper-small.en.int8/small.en-decoder.int8.onnx
    # - assets/models/sherpa-onnx-whisper-small.en.int8/small.en-encoder.int8.onnx
    # - assets/models/sherpa-onnx-whisper-small.en.int8/small.en-tokens.txt

    # - assets/models/sherpa-onnx-whisper-turbo/turbo-decoder.int8.onnx
    # - assets/models/sherpa-onnx-whisper-turbo/turbo-encoder.int8.onnx
    # - assets/models/sherpa-onnx-whisper-turbo/turbo-tokens.txt

    # Online Models
    # 1. Nemo Streaming Fast Conformer Transducer
    - assets/models/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms/encoder.onnx
    - assets/models/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms/decoder.onnx
    - assets/models/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms/joiner.onnx
    - assets/models/sherpa-onnx-nemo-streaming-fast-conformer-transducer-en-1040ms/tokens.txt

    # 2. Streaming Zipformer (2023-06-21) - Regular and Int8
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/encoder-epoch-99-avg-1.int8.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/decoder-epoch-99-avg-1.int8.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/joiner-epoch-99-avg-1.int8.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-21/tokens.txt

    # 3. Streaming Zipformer (2023-06-26) - Regular and Int8
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/encoder-epoch-99-avg-1-chunk-16-left-128.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/decoder-epoch-99-avg-1-chunk-16-left-128.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/joiner-epoch-99-avg-1-chunk-16-left-128.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/encoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/decoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/joiner-epoch-99-avg-1-chunk-16-left-128.int8.onnx
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/tokens.txt
    - assets/models/sherpa-onnx-streaming-zipformer-en-2023-06-26/bpe.model

    # Keyword Spotting
    # 1. Gigaspeech Zipformer (2024-01-01) - Int8
    # - assets/models/sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01/encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx
    # - assets/models/sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01/decoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx
    # - assets/models/sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01/joiner-epoch-12-avg-2-chunk-16-left-64.int8.onnx
    # - assets/models/sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01/tokens.txt
    # - assets/models/sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01/bpe.model
    # - assets/models/sherpa-onnx-kws-zipformer-gigaspeech-3.3M-2024-01-01/keywords.txt

    # VAD
    - assets/models/silero_vad.onnx

    # Test files for dictation (all available test WAVs and transcripts)
    - assets/dictation_test/
    - assets/dictation_test/test_files/
